language: c
script: make && make test
build: make

compiler: 
  - clang
  - gcc

addons:
        apt:
                packages:
                        - clang
                        - libconfig-dev
